(library
 (name camlstar)
 (wrapped false)
 (libraries z3)
 (modules ast lexer parser parse unify subst shape infer vc check smtlib axioms anf nnf relabs skolem smt))

(ocamllex lexer)

(menhir
 (modules parser)
 (flags (--explain)))

(executable
 (name parse_test)
 (modules parse_test)
 (libraries camlstar))

(executable
 (name infer_test)
 (modules infer_test)
 (libraries camlstar))

(executable
 (name main)
 (modules main)
 (libraries camlstar))
