(library
 (name camlstar)
 (wrapped false)
 (modules ast lexer parser parse unify infer))

(ocamllex lexer)

(menhir
 (modules parser)
 (flags (--explain)))

(executable
 (name parse_test)
 (modules parse_test)
 (libraries camlstar))

(executable
 (name infer_test)
 (modules infer_test)
 (libraries camlstar))
